### ISSUE TITLE
Develop best practice for working with OSS (dasein)

### ISSUE THREAD

**Issue by ckelner** [TheWeatherCompany/dasein-cloud-aws#51]
https://gist.github.com/ckelner/738175518368bd023bc2
1. In TWC fork create branch for new functionality/bug-fix
2. Make changes in branch
3. Issue PR request from branch in TWC fork to dasein
4. Issue PR request from branch in TWC fork to TWC develop branch (so changes can go into production without waiting for dasein to accept PR)
5. Wait for PR request to dasein to be accepted
6. Observe diff between TWC fork develop branch and Dasein develop branch
7. Discuss observation
8. Determine if this method of working is valid or alter and test again.

**Comment by ckelner** [comment]
Here you can see our PR:
https://github.com/greese/dasein-cloud-aws/pull/75

And here you can see that once the PR(s) have been accepted and we do a diff between the TWC branch and the Dasein Branch that git recognizes "differences".
![screen shot 2013-12-16 at 5 29 48 pm](https://f.cloud.github.com/assets/133862/1759618/aabe1bfc-66a1-11e3-8952-db8a40a75964.png)

Are we ok with this and just making a PR to pull in these 'merges'?  Thoughts @clstokes?

See: https://github.com/TheWeatherCompany/dasein-cloud-aws/pull/57

**Comment by clstokes** [comment]
The impact of this is that we'll lose the granular commit history and only see the "Merge pull request..." messages in our commit log, is that right?

**Comment by ckelner** [comment]
Well that is true yes.  I am more less annoyed that git doesn't recognize that the differences between TWC dasein-cloud-aws fork and the Greese dasein-cloud-aws repo are pull requests from TWC branches and have already been merged back into develop.  You can see that it recognizes that there are "0 changed files with 0 additions and 0 deletions" yet it wants to merge the "3 commits" that were PR requests generated from TWC.

**Comment by clstokes** [comment]
Ah, I see that now. Hmm, I guess it still has to record a change in the git commit history, so maybe that's why it still needs to be merge, to "move" HEAD to the latest commit ref...

**Comment by ckelner** [comment]
I think I am ok with it, just annoying, but your explanation does make sense.  Should we continue working this way in the future then?

**Comment by clstokes** [comment]
I think so.

**Comment by ckelner** [comment]
Closing!
