### ISSUE TITLE
Add deprecated flag for machine types.

### ISSUE THREAD

**Issue by clstokes** [TheWeatherCompany/dasein-cloud-aws#83]
Add a deprecated flag to machine types marked as "previous generation" from this post - http://aws.typepad.com/aws/2014/04/ec2-update-previous-generation-instances.html. This will require corresponding changes to the model class in dasein-cloud-core.

**Comment by armondhonore** [comment]
@clstokes are you looking for this to be returned as a value the api call?

**Comment by clstokes** [comment]
Yes. From dasein and our API.

On Apr 24, 2014, at 5:22, Armond Honore notifications@github.com wrote:

@clstokes https://github.com/clstokes are you looking for this to be
returned as a value the api call?

—
Reply to this email directly or view it on
GitHubhttps://github.com/TheWeatherCompany/dasein-cloud-aws/issues/83#issuecomment-41273324
.

**Comment by armondhonore** [comment]
@clstokes hope you had your coffee before you responded to this!! 7 hours of between emails! Really?

**Comment by ckelner** [comment]
@clstokes @armondhonore This was added right? Can close?

**Comment by ghost** [comment]
@clstokes and @ckelner yes this was added
